version: '3.8'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_volume:/data
    restart: on-failure

  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/test && /usr/bin/minio server --console-address :9001 /data'
    volumes:
      - minio_volume:/data
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "{{ cookiecutter.minio_root_user }}"
      MINIO_ROOT_PASSWORD: "{{ cookiecutter.minio_root_password }}"
    restart: on-failure

volumes:
  redis_volume:
  minio_volume:
